Missing functionality in scryer
cmpute/dashu pull request #35
Opened 2023-08-30 04:24 UTC by fayeed

@cmpute This PR includes all the missing functionality that the Scryer needs that I had to add, please let me know if the implementation makes sense to you or needs to be updated.

2023-08-30 04:54 UTC, cmpute requested changes
In short, I'm afraid that I can't merge these changes directly. However, I would love to use this PR as a thread to discuss how I should change the `dashu` crates to fit your demand.

Most of the changes proposed in this PR are not necessary (such as proposing new functions for conversions and comparison). The only functions that might be necessary are `RBig::is_integer`, `IBig::count_ones`, `IBig::is_odd`. I will add the first one in the next release, but I'm not very satisfied with the other two...

2023-08-30 04:54 UTC, cmpute commented on integer/src/bits.rs
> +    pub fn count_ones(&self) -> usize {
Why would you need the functionality to count ones on a signed integer? The implementation here doesn't make sense to me as well...

2023-08-30 04:54 UTC, cmpute commented on integer/src/cmp.rs
> +macro_rules! impl_partial_ord_for_prim_ints {
For comparison between different types, it's designed to use the `num-order` crate right now. Could you please take a look at that crate and use the `num_cmp` and `num_eq` functions provided in that crate?

2023-08-30 04:54 UTC, cmpute commented on integer/src/convert.rs
> +
The intended way to convert big integers into small integers is through the `TryFrom` APIs, there is no need to create standalone functions. (besides, convert to floats first is very inefficient).

To do a narrowing conversion, you can do: `let small: i32 = big.try_into().unwrap()`

2023-08-30 04:54 UTC, cmpute commented on integer/src/div_const.rs
> +
Same as above, please use the crate `num-order` instead.

2023-08-30 04:54 UTC, cmpute commented on Cargo.toml
> +default = ["std", "num-order", "num-traits", "num-traits_v02"]
Unfortunately I will not accept adding `num-traits` as a default dependency. Please specify the dependency in your own Cargo.toml

2023-08-30 04:54 UTC, cmpute commented on integer/src/ibig.rs
> +    #[inline]
Are you aware of the [DivRem](https://docs.rs/dashu-base/latest/dashu_base/ring/trait.DivRem.html) and [DivRemEuclid](https://docs.rs/dashu-base/latest/dashu_base/ring/trait.DivRemEuclid.html) trait provided in the `dashu-base` crate?

2023-08-30 04:54 UTC, cmpute commented on integer/src/ubig.rs
> +    pub fn repr(&self) -> TypedReprRef<'_> {
Where do you need to access this private representation? This type is not intended for outside use.

2023-08-30 04:54 UTC, cmpute commented on integer/src/ibig.rs
> +    pub fn is_odd(&self) -> bool {
Is it necessary to have a standalone function for this? You can test it by taking the first bit, which is very fast.

2023-08-30 04:56 UTC, cmpute commented
And I apologize that the documentations for `dashu` are pretty bad right now. I do plan to write a guide about how to use these crates, but I haven't finished it yet, and I expect it to take another 3 months or so..

2023-08-30 05:03 UTC, fayeed commented
@cmpute No worries, I am still a beginner in Rust, Scryer & Dashu was the first proper Rust codebase I looked through missed a lot of things, anyway Thanks for the help with this.

2023-08-31 12:38 UTC, cmpute commented
> @cmpute How do I compare `RBig` with `IBig` looks like only `IBig` implements `NumOrd`, thanks.

Ah yes, I'm working on implementing that between Ubig/IBig and Rbig

2023-08-31 19:28 UTC, cmpute commented
The latest commit on the `dashu` repo now contains the implementation of `NumOrd<IBig>` for `RBig`.

2023-09-10 03:48 UTC, cmpute commented
I have completed all the break changes I would like to include in the next version (v0.4) of `dashu` and it's ready for release. You can compose the PR based on the latest commit on the master branch. I would like to coordinate with you and see if you want to see more features to the next release of `dashu`. Thanks.

2023-09-11 09:16 UTC, fayeed commented
Hey, I am PR open with the master on Scryer now, was able to get everything working, if you can release a new version I could update the PR with it, thanks.

2023-09-12 06:25 UTC, closed without merging

2023-09-12 06:25 UTC, cmpute commented
I have released the v0.4 of `dashu` crates. Thanks for your work on Scryer side!